"use client";

import type {
  AiInsightsReport,
  AiInsightsResponse,
} from "@/lib/ai-insights-contract";

export type AiInsightsPdfReport = AiInsightsReport;

export type AiInsightsPdfOptions = {
  companyId?: string;
  companyLabel?: string;
  exportedAt?: Date;
  filename?: string;
};

export type AiInsightsPdfExportResult = {
  filename: string;
  pageCount: number;
};

export type AiInsightsPdfMetadataEntry = {
  label: string;
  value: string;
};

export type AiInsightsPdfBlock =
  | {
      kind: "section";
      eyebrow: string;
      startOnNewPage: boolean;
      title: string;
    }
  | {
      kind: "item-heading";
      eyebrow: string;
      title: string;
    }
  | {
      emphasis?: boolean;
      kind: "paragraph";
      label?: string;
      text: string;
      tone?: "default" | "muted" | "warning";
    }
  | {
      entries: AiInsightsPdfMetadataEntry[];
      kind: "metadata";
    }
  | {
      items: string[];
      kind: "list";
      label?: string;
      ordered?: boolean;
      tone?: "default" | "muted" | "warning";
    };

type PdfDocument = import("jspdf").jsPDF;

type PdfRenderState = {
  bodyBottom: number;
  bodyTop: number;
  contentWidth: number;
  doc: PdfDocument;
  exportedAt: Date;
  pageHeight: number;
  pageWidth: number;
  report: AiInsightsPdfReport;
  sectionTitle: string;
  x: number;
  y: number;
};

type PdfTextStyle = {
  bold?: boolean;
  color?: string;
  fontSize: number;
  lineHeight: number;
};

const COLORS = {
  accent: "1267C4",
  accentDark: "0B4F96",
  border: "D8E3F2",
  dark: "13233A",
  muted: "526477",
  softAccent: "EAF4FF",
  softMuted: "F7F9FC",
  warning: "9A6700",
  warningBackground: "FFF8E6",
} as const;

const PAGE_MARGIN_X = 44;
const PAGE_BODY_TOP = 86;
const PAGE_FOOTER_HEIGHT = 52;

const PRIORITY_ORDER: Record<
  AiInsightsResponse["actions"][number]["priority"],
  number
> = {
  imediata: 0,
  alta: 1,
  media: 2,
  baixa: 3,
};

/**
 * Creates and downloads a text-based PDF. No DOM capture, canvas screenshot or
 * browser print pipeline is involved, so long reports remain crisp and searchable.
 */
export async function exportAiInsightsToPdf(
  report: AiInsightsPdfReport,
  options: AiInsightsPdfOptions = {},
): Promise<AiInsightsPdfExportResult> {
  const { doc, filename } = await createAiInsightsPdfDocument(report, options);
  const pageCount = doc.getNumberOfPages();
  doc.save(filename);
  return { filename, pageCount };
}

/**
 * Kept separate from the download operation for deterministic integration tests
 * and for callers that may later upload the generated bytes instead of saving it.
 */
export async function createAiInsightsPdfDocument(
  report: AiInsightsPdfReport,
  options: AiInsightsPdfOptions = {},
) {
  const exportedAt = validDate(options.exportedAt) ?? new Date();
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    format: "a4",
    orientation: "portrait",
    unit: "pt",
  });
  const filename = options.filename
    ? ensurePdfExtension(safeAiInsightsPdfFilename(options.filename))
    : createAiInsightsPdfFilename(report, exportedAt, options.companyLabel);
  const companyLabel = cleanPdfText(
    options.companyLabel || options.companyId || "",
  );

  doc.setProperties({
    author: "IPXData",
    creator: "IPXData",
    keywords: "IPXData, IA Advisor, inteligência operacional, plano de ação",
    subject: `${companyLabel ? `${companyLabel} · ` : ""}${moduleLabel(report.insights.source.module)} · ${surfaceLabel(report.insights.source.surface)} · ${report.insights.period.label}`,
    title: `IA Advisor · ${companyLabel ? `${companyLabel} · ` : ""}${report.insights.source.reportTitle}`,
  });

  renderAiInsightsPdf(doc, report, exportedAt, options);
  return { doc, filename };
}

export function buildAiInsightsPdfBlocks(
  report: AiInsightsPdfReport,
  options: Pick<AiInsightsPdfOptions, "companyId" | "companyLabel"> = {},
): AiInsightsPdfBlock[] {
  const { insights, meta } = report;
  const periodRange = civilPeriodRange(insights);
  const timeZone = certifiedIanaTimeZone(insights.period.timeZone);
  const actions = [...insights.actions].sort(
    (left, right) =>
      PRIORITY_ORDER[left.priority] - PRIORITY_ORDER[right.priority],
  );
  const blocks: AiInsightsPdfBlock[] = [
    {
      eyebrow: "IA ADVISOR · DIREÇÃO EXECUTIVA",
      kind: "section",
      startOnNewPage: false,
      title: "Plano de resultado",
    },
    {
      entries: [
        ...(options.companyLabel || options.companyId
          ? [
              {
                label: "Empresa",
                value: cleanPdfText(
                  options.companyLabel || options.companyId || "",
                ),
              },
            ]
          : []),
        {
          label: "Visão de origem",
          value: cleanPdfText(insights.source.reportTitle),
        },
        {
          label: "Módulo / visão",
          value: `${moduleLabel(insights.source.module)} · ${surfaceLabel(insights.source.surface)}`,
        },
        { label: "Período analisado", value: cleanPdfText(insights.period.label) },
        ...(periodRange
          ? [{ label: "Intervalo civil", value: periodRange }]
          : []),
        {
          label: "Dados consolidados até",
          value: insights.source.dataCompleteUntil
            ? formatAiInsightsPdfDateTime(
                insights.source.dataCompleteUntil,
                timeZone,
              )
            : "Corte temporal não certificado",
        },
        {
          label: "Plano gerado em",
          value: formatAiInsightsPdfDateTime(meta.generatedAt, timeZone),
        },
      ],
      kind: "metadata",
    },
    {
      emphasis: true,
      kind: "paragraph",
      label: "Tese de resultado",
      text: contentOrFallback(
        insights.summary,
        "A análise não apresentou uma conclusão executiva.",
      ),
    },
  ];

  if (actions[0]) {
    blocks.push({
      emphasis: true,
      kind: "paragraph",
      label: "Próximo movimento",
      text: `${contentOrFallback(actions[0].title, "Ação prioritária")}. ${contentOrFallback(actions[0].expectedEffect, "Impacto a validar")}. Validar em ${contentOrFallback(actions[0].measurementWindow, "janela comparável")}.`,
    });
  }

  blocks.push({
    eyebrow: `${insights.findings.length} ALAVANCA(S)`,
    kind: "section",
    startOnNewPage: true,
    title: "Alavancas de resultado",
  });

  if (!insights.findings.length) {
    blocks.push({
      kind: "paragraph",
      text: "O período não sustentou uma alavanca de resultado com força suficiente.",
      tone: "muted",
    });
  }

  insights.findings.forEach((finding, index) => {
    blocks.push(
      {
        eyebrow: `ALAVANCA ${index + 1} · FORÇA DO SINAL ${confidenceLabel(finding.confidence).toUpperCase()}`,
        kind: "item-heading",
        title: contentOrFallback(finding.title, `Alavanca ${index + 1}`),
      },
      {
        entries: [
          { label: "Força do sinal", value: confidenceLabel(finding.confidence) },
          {
            label: "Origem na visão",
            value: finding.widget
              ? cleanPdfText(finding.widget)
              : "Visão consolidada",
          },
        ],
        kind: "metadata",
      },
      {
        kind: "paragraph",
        label: "Sinal observado",
        text: contentOrFallback(finding.evidence, "Sinal não informado."),
      },
      {
        kind: "paragraph",
        label: "Implicação para o próximo ciclo",
        text: contentOrFallback(
          finding.interpretation,
          "Implicação futura não informada.",
        ),
        tone: "muted",
      },
    );
  });

  blocks.push({
    eyebrow: `${actions.length} INICIATIVA(S) PRIORIZADA(S)`,
    kind: "section",
    startOnNewPage: true,
    title: "Plano para capturar o resultado",
  });

  if (!actions.length) {
    blocks.push({
      kind: "paragraph",
      text: "O período não sustentou uma iniciativa prática com força suficiente.",
      tone: "muted",
    });
  }

  actions.forEach((action, index) => {
    blocks.push(
      {
        eyebrow: `INICIATIVA ${index + 1} · PRIORIDADE ${priorityLabel(action.priority).toUpperCase()}`,
        kind: "item-heading",
        title: contentOrFallback(action.title, `Iniciativa ${index + 1}`),
      },
      {
        kind: "paragraph",
        label: "Por que pode mover o resultado",
        text: contentOrFallback(action.whyNow, "Justificativa não informada."),
      },
      {
        items: action.steps.map((step) => cleanPdfText(step)),
        kind: "list",
        label: "Execução",
        ordered: true,
      },
      {
        emphasis: true,
        kind: "paragraph",
        label: "Impacto a validar",
        text: contentOrFallback(
          action.expectedEffect,
          "Resultado esperado não informado.",
        ),
      },
      {
        entries: [
          {
            label: "KPI",
            value: action.targetKpi
              ? cleanPdfText(action.targetKpi)
              : "A definir no piloto",
          },
          {
            label: "Ponto de partida",
            value: action.baseline
              ? cleanPdfText(action.baseline)
              : "A medir",
          },
          {
            label: "Meta do piloto",
            value: action.target
              ? cleanPdfText(action.target)
              : "A definir no piloto",
          },
          {
            label: "Prazo de validação",
            value: contentOrFallback(
              action.measurementWindow,
              "Não informada",
            ),
          },
          {
            label: "Dono sugerido",
            value: action.owner ? cleanPdfText(action.owner) : "A definir",
          },
          { label: "Esforço", value: effortLabel(action.effort) },
          { label: "Confiança", value: confidenceLabel(action.confidence) },
        ],
        kind: "metadata",
      },
    );

    if (action.risks.length) {
      blocks.push({
        items: action.risks.map((risk) => cleanPdfText(risk)),
        kind: "list",
        label: "Condições para funcionar",
        tone: "warning",
      });
    }
  });

  const hasMaterialPremises =
    insights.dataQuality.status !== "suficiente" ||
    insights.dataQuality.notes.length > 0 ||
    insights.questions.length > 0;
  if (hasMaterialPremises) {
    blocks.push({
      eyebrow: "APÊNDICE",
      kind: "section",
      startOnNewPage: true,
      title: "Base e premissas",
    });
    if (insights.dataQuality.notes.length) {
      blocks.push({
        items: insights.dataQuality.notes.map((note) => cleanPdfText(note)),
        kind: "list",
        label: "Premissas materiais",
        tone: "muted",
      });
    }
    if (insights.questions.length) {
      blocks.push({
        items: insights.questions.map((question) => cleanPdfText(question)),
        kind: "list",
        label: "O que destrava a próxima decisão",
        ordered: true,
      });
    }
  }

  blocks.push({
    kind: "paragraph",
    label: "Nota de responsabilidade",
    text: contentOrFallback(
      insights.disclaimer,
      "As recomendações devem ser validadas com acompanhamento dos indicadores definidos.",
    ),
    tone: "muted",
  });

  return blocks;
}

export function splitAiInsightsPdfLines<T>(
  lines: readonly T[],
  capacity: number,
): { remaining: T[]; visible: T[] } {
  const safeCapacity = Math.max(0, Math.floor(capacity));
  return {
    remaining: lines.slice(safeCapacity),
    visible: lines.slice(0, safeCapacity),
  };
}

export function safeAiInsightsPdfFilename(value: string) {
  const withoutExtension = value.trim().replace(/\.pdf$/i, "");
  return (
    withoutExtension
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-zA-Z0-9-_]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 120)
      .toLowerCase() || "ia-advisor"
  );
}

export function createAiInsightsPdfFilename(
  report: AiInsightsPdfReport,
  exportedAt: Date,
  companyLabel?: string,
) {
  const { insights } = report;
  const companySegment = companyLabel
    ? `${safeAiInsightsPdfFilename(companyLabel).slice(0, 48)}-`
    : "";
  const date = civilDateKey(
    validDate(exportedAt) ?? new Date(0),
    certifiedIanaTimeZone(insights.period.timeZone),
  );
  return ensurePdfExtension(
    safeAiInsightsPdfFilename(
      `ia-advisor-${companySegment}${insights.source.module}-${insights.source.surface}-${date}`,
    ),
  );
}

export function formatAiInsightsPdfDateTime(
  value: string | Date,
  timeZone: string,
) {
  const date = value instanceof Date ? validDate(value) : validDate(new Date(value));
  if (!date) return cleanPdfText(String(value));
  return new Intl.DateTimeFormat("pt-BR", {
    dateStyle: "short",
    timeStyle: "short",
    timeZone: certifiedIanaTimeZone(timeZone),
  }).format(date);
}

function renderAiInsightsPdf(
  doc: PdfDocument,
  report: AiInsightsPdfReport,
  exportedAt: Date,
  options: Pick<AiInsightsPdfOptions, "companyId" | "companyLabel">,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const state: PdfRenderState = {
    bodyBottom: pageHeight - PAGE_FOOTER_HEIGHT,
    bodyTop: PAGE_BODY_TOP,
    contentWidth: pageWidth - PAGE_MARGIN_X * 2,
    doc,
    exportedAt,
    pageHeight,
    pageWidth,
    report,
    sectionTitle: "Plano de resultado",
    x: PAGE_MARGIN_X,
    y: PAGE_BODY_TOP,
  };

  drawPageHeader(state);
  const blocks = buildAiInsightsPdfBlocks(report, options);
  blocks.forEach((block) => renderBlock(state, block));
  drawPageFooters(state);
}

function renderBlock(state: PdfRenderState, block: AiInsightsPdfBlock) {
  if (block.kind === "section") {
    state.sectionTitle = block.title;
    if (block.startOnNewPage) addPage(state);
    drawSectionHeading(state, block.eyebrow, block.title);
    return;
  }
  if (block.kind === "item-heading") {
    drawItemHeading(state, block.eyebrow, block.title);
    return;
  }
  if (block.kind === "metadata") {
    drawMetadata(state, block.entries);
    return;
  }
  if (block.kind === "list") {
    drawList(state, block);
    return;
  }
  drawParagraph(state, block);
}

function drawPageHeader(state: PdfRenderState) {
  const { doc, pageWidth } = state;
  doc.setFillColor(`#${COLORS.accent}`);
  doc.rect(0, 0, pageWidth, 10, "F");
  drawText(doc, "IPXData", PAGE_MARGIN_X, 34, 10, COLORS.accent, true);
  drawText(
    doc,
    "IA ADVISOR",
    pageWidth - PAGE_MARGIN_X,
    34,
    8,
    COLORS.accent,
    true,
    "right",
  );
  drawText(
    doc,
    state.sectionTitle,
    PAGE_MARGIN_X,
    57,
    15,
    COLORS.dark,
    true,
  );
  doc.setDrawColor(`#${COLORS.border}`);
  doc.line(PAGE_MARGIN_X, 70, pageWidth - PAGE_MARGIN_X, 70);
}

function drawPageFooters(state: PdfRenderState) {
  const { doc, pageHeight, pageWidth, report } = state;
  const pageCount = doc.getNumberOfPages();
  const timeZone = certifiedIanaTimeZone(report.insights.period.timeZone);
  const exportedLabel = `Exportado em ${formatAiInsightsPdfDateTime(state.exportedAt, timeZone)}`;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(`#${COLORS.border}`);
    doc.line(
      PAGE_MARGIN_X,
      pageHeight - 36,
      pageWidth - PAGE_MARGIN_X,
      pageHeight - 36,
    );
    drawText(
      doc,
      "IPXData · IA Advisor",
      PAGE_MARGIN_X,
      pageHeight - 18,
      7.5,
      COLORS.muted,
      true,
    );
    drawText(
      doc,
      exportedLabel,
      pageWidth / 2,
      pageHeight - 18,
      7.5,
      COLORS.muted,
      false,
      "center",
    );
    drawText(
      doc,
      `Página ${page} de ${pageCount}`,
      pageWidth - PAGE_MARGIN_X,
      pageHeight - 18,
      7.5,
      COLORS.muted,
      true,
      "right",
    );
  }
}

function drawSectionHeading(
  state: PdfRenderState,
  eyebrow: string,
  title: string,
) {
  ensureSpace(state, 60);
  drawText(
    state.doc,
    cleanPdfText(eyebrow).toUpperCase(),
    state.x,
    state.y + 8,
    8,
    COLORS.accent,
    true,
  );
  state.y += 17;
  drawFlowText(state, cleanPdfText(title), state.x, state.contentWidth, {
    bold: true,
    color: COLORS.dark,
    fontSize: 19,
    lineHeight: 23,
  });
  state.doc.setDrawColor(`#${COLORS.accent}`);
  state.doc.setLineWidth(2);
  state.doc.line(state.x, state.y + 3, state.x + 46, state.y + 3);
  state.doc.setLineWidth(0.2);
  state.y += 18;
}

function drawItemHeading(
  state: PdfRenderState,
  eyebrow: string,
  title: string,
) {
  ensureSpace(state, 58);
  if (state.y > state.bodyTop + 12) {
    state.doc.setDrawColor(`#${COLORS.border}`);
    state.doc.line(state.x, state.y, state.x + state.contentWidth, state.y);
    state.y += 18;
  }
  drawText(
    state.doc,
    cleanPdfText(eyebrow).toUpperCase(),
    state.x,
    state.y + 7,
    7.5,
    COLORS.accent,
    true,
  );
  state.y += 16;
  drawFlowText(state, cleanPdfText(title), state.x, state.contentWidth, {
    bold: true,
    color: COLORS.dark,
    fontSize: 13,
    lineHeight: 17,
  });
  state.y += 8;
}

function drawMetadata(
  state: PdfRenderState,
  entries: AiInsightsPdfMetadataEntry[],
) {
  const columnGap = 10;
  const columnWidth = (state.contentWidth - columnGap) / 2;
  for (let index = 0; index < entries.length; index += 2) {
    const row = entries.slice(index, index + 2);
    const measurements = row.map((entry) => {
      const lines = wrapPdfText(
        state.doc,
        contentOrFallback(entry.value, "Não informado"),
        columnWidth - 20,
        9.5,
        false,
      );
      return { entry, lines };
    });
    const rowHeight = Math.max(
      48,
      ...measurements.map(({ lines }) => 27 + lines.length * 12),
    );

    if (rowHeight > state.bodyBottom - state.bodyTop) {
      measurements.forEach(({ entry }) => {
        drawParagraph(state, {
          kind: "paragraph",
          label: entry.label,
          text: contentOrFallback(entry.value, "Não informado"),
        });
      });
      continue;
    }

    ensureSpace(state, rowHeight + 8);
    measurements.forEach(({ entry, lines }, columnIndex) => {
      const x = state.x + columnIndex * (columnWidth + columnGap);
      state.doc.setFillColor(`#${COLORS.softMuted}`);
      state.doc.setDrawColor(`#${COLORS.border}`);
      state.doc.roundedRect(x, state.y, columnWidth, rowHeight, 4, 4, "FD");
      drawText(
        state.doc,
        cleanPdfText(entry.label).toUpperCase(),
        x + 10,
        state.y + 15,
        7,
        COLORS.muted,
        true,
      );
      setTextStyle(state.doc, {
        color: COLORS.dark,
        fontSize: 9.5,
        lineHeight: 12,
      });
      state.doc.text(lines, x + 10, state.y + 31, {
        lineHeightFactor: 12 / 9.5,
      });
    });
    state.y += rowHeight + 8;
  }
  state.y += 4;
}

function drawParagraph(
  state: PdfRenderState,
  block: Extract<AiInsightsPdfBlock, { kind: "paragraph" }>,
) {
  const style = paragraphStyle(block.tone);
  const labelHeight = block.label ? 18 : 0;
  const lines = wrapPdfText(
    state.doc,
    contentOrFallback(block.text, "Não informado."),
    block.emphasis ? state.contentWidth - 24 : state.contentWidth,
    style.fontSize,
    false,
  );
  const boxHeight = labelHeight + lines.length * style.lineHeight + 22;

  if (
    block.emphasis &&
    boxHeight <= state.bodyBottom - state.bodyTop
  ) {
    ensureSpace(state, boxHeight + 8);
    state.doc.setFillColor(`#${COLORS.softAccent}`);
    state.doc.setDrawColor(`#${COLORS.border}`);
    state.doc.roundedRect(
      state.x,
      state.y,
      state.contentWidth,
      boxHeight,
      5,
      5,
      "FD",
    );
    let textY = state.y + 15;
    if (block.label) {
      drawText(
        state.doc,
        cleanPdfText(block.label).toUpperCase(),
        state.x + 12,
        textY,
        7.5,
        COLORS.accentDark,
        true,
      );
      textY += labelHeight;
    }
    setTextStyle(state.doc, style);
    state.doc.text(lines, state.x + 12, textY, {
      lineHeightFactor: style.lineHeight / style.fontSize,
    });
    state.y += boxHeight + 12;
    return;
  }

  ensureSpace(state, labelHeight + style.lineHeight + 8);
  if (block.label) {
    drawText(
      state.doc,
      cleanPdfText(block.label).toUpperCase(),
      state.x,
      state.y + 8,
      7.5,
      block.tone === "warning" ? COLORS.warning : COLORS.muted,
      true,
    );
    state.y += labelHeight;
  }
  drawFlowLines(state, lines, state.x, style);
  state.y += 12;
}

function drawList(
  state: PdfRenderState,
  block: Extract<AiInsightsPdfBlock, { kind: "list" }>,
) {
  const style = paragraphStyle(block.tone);
  if (block.label) {
    ensureSpace(state, 18 + style.lineHeight);
    drawText(
      state.doc,
      cleanPdfText(block.label).toUpperCase(),
      state.x,
      state.y + 8,
      7.5,
      block.tone === "warning" ? COLORS.warning : COLORS.muted,
      true,
    );
    state.y += 20;
  }

  block.items.forEach((item, index) => {
    ensureSpace(state, style.lineHeight + 4);
    const prefix = block.ordered ? `${index + 1}.` : "•";
    const indent = block.ordered ? 24 : 18;
    const lines = wrapPdfText(
      state.doc,
      contentOrFallback(item, "Não informado."),
      state.contentWidth - indent,
      style.fontSize,
      false,
    );
    let remaining = lines;
    let firstChunk = true;

    while (remaining.length) {
      let capacity = availableLineCapacity(state, style.lineHeight);
      if (capacity < 1) {
        addPage(state);
        capacity = availableLineCapacity(state, style.lineHeight);
      }
      const chunk = splitAiInsightsPdfLines(remaining, capacity);
      setTextStyle(state.doc, style);
      if (firstChunk) {
        state.doc.text(prefix, state.x, state.y + style.fontSize);
      }
      state.doc.text(chunk.visible, state.x + indent, state.y + style.fontSize, {
        lineHeightFactor: style.lineHeight / style.fontSize,
      });
      state.y += chunk.visible.length * style.lineHeight;
      remaining = chunk.remaining;
      firstChunk = false;
    }
    state.y += 5;
  });
  state.y += 7;
}

function drawFlowText(
  state: PdfRenderState,
  text: string,
  x: number,
  width: number,
  style: PdfTextStyle,
) {
  const lines = wrapPdfText(
    state.doc,
    contentOrFallback(text, "Não informado."),
    width,
    style.fontSize,
    Boolean(style.bold),
  );
  drawFlowLines(state, lines, x, style);
}

function drawFlowLines(
  state: PdfRenderState,
  lines: string[],
  x: number,
  style: PdfTextStyle,
) {
  let remaining = lines;
  while (remaining.length) {
    let capacity = availableLineCapacity(state, style.lineHeight);
    if (capacity < 1) {
      addPage(state);
      capacity = availableLineCapacity(state, style.lineHeight);
    }
    const chunk = splitAiInsightsPdfLines(remaining, capacity);
    setTextStyle(state.doc, style);
    state.doc.text(chunk.visible, x, state.y + style.fontSize, {
      lineHeightFactor: style.lineHeight / style.fontSize,
    });
    state.y += chunk.visible.length * style.lineHeight;
    remaining = chunk.remaining;
  }
}

function wrapPdfText(
  doc: PdfDocument,
  text: string,
  width: number,
  fontSize: number,
  bold: boolean,
) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(fontSize);
  const paragraphs = cleanPdfText(text).split("\n");
  return paragraphs.flatMap((paragraph, index) => {
    const lines = paragraph.trim()
      ? (doc.splitTextToSize(paragraph, width) as string[])
      : [" "];
    return index < paragraphs.length - 1 ? [...lines, " "] : lines;
  });
}

function ensureSpace(state: PdfRenderState, requiredHeight: number) {
  const maximumBodyHeight = state.bodyBottom - state.bodyTop;
  const safeRequiredHeight = Math.min(requiredHeight, maximumBodyHeight);
  if (state.y + safeRequiredHeight > state.bodyBottom) addPage(state);
}

function availableLineCapacity(state: PdfRenderState, lineHeight: number) {
  return Math.max(0, Math.floor((state.bodyBottom - state.y) / lineHeight));
}

function addPage(state: PdfRenderState) {
  state.doc.addPage("a4", "portrait");
  state.y = state.bodyTop;
  drawPageHeader(state);
}

function setTextStyle(doc: PdfDocument, style: PdfTextStyle) {
  doc.setFont("helvetica", style.bold ? "bold" : "normal");
  doc.setFontSize(style.fontSize);
  doc.setTextColor(`#${style.color ?? COLORS.dark}`);
}

function drawText(
  doc: PdfDocument,
  text: string,
  x: number,
  y: number,
  size: number,
  color: string,
  bold = false,
  align: "left" | "center" | "right" = "left",
) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(size);
  doc.setTextColor(`#${color}`);
  doc.text(cleanPdfText(text), x, y, { align });
}

function paragraphStyle(
  tone: Extract<AiInsightsPdfBlock, { kind: "paragraph" | "list" }>["tone"],
): PdfTextStyle {
  return {
    color:
      tone === "warning"
        ? COLORS.warning
        : tone === "muted"
          ? COLORS.muted
          : COLORS.dark,
    fontSize: 10,
    lineHeight: 14,
  };
}

function cleanPdfText(value: string) {
  return String(value ?? "")
    .replace(/\r\n?/g, "\n")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, " ")
    .trim();
}

function contentOrFallback(value: string, fallback: string) {
  return cleanPdfText(value) || fallback;
}

function civilPeriodRange(insights: AiInsightsResponse) {
  const { from, to } = insights.period;
  if (from && to) return from === to ? from : `${from} a ${to}`;
  return from ?? to ?? null;
}

function certifiedIanaTimeZone(value: string) {
  const candidate = value.trim();
  if (!candidate) return "UTC";
  try {
    new Intl.DateTimeFormat("pt-BR", { timeZone: candidate }).format(
      new Date(0),
    );
    return candidate;
  } catch {
    return "UTC";
  }
}

function civilDateKey(value: Date, timeZone: string) {
  const parts = new Intl.DateTimeFormat("en-US", {
    day: "2-digit",
    month: "2-digit",
    timeZone,
    year: "numeric",
  }).formatToParts(value);
  const part = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((item) => item.type === type)?.value ?? "00";
  return `${part("year")}-${part("month")}-${part("day")}`;
}

function validDate(value: Date | undefined | null) {
  return value instanceof Date && Number.isFinite(value.getTime()) ? value : null;
}

function ensurePdfExtension(value: string) {
  return `${value.replace(/\.pdf$/i, "") || "ia-advisor"}.pdf`;
}

function moduleLabel(module: AiInsightsResponse["source"]["module"]) {
  return module === "counting" ? "Contagem" : "Ocupação";
}

function surfaceLabel(surface: AiInsightsResponse["source"]["surface"]) {
  if (surface === "live") return "Ao Vivo";
  if (surface === "analysis") return "Análises";
  return "Relatórios";
}

function priorityLabel(
  priority: AiInsightsResponse["actions"][number]["priority"],
) {
  if (priority === "imediata") return "Imediata";
  if (priority === "alta") return "Alta";
  if (priority === "media") return "Média";
  return "Baixa";
}

function confidenceLabel(
  confidence:
    | AiInsightsResponse["findings"][number]["confidence"]
    | AiInsightsResponse["actions"][number]["confidence"],
) {
  if (confidence === "alta") return "Alta";
  if (confidence === "media") return "Média";
  return "Baixa";
}

function effortLabel(effort: AiInsightsResponse["actions"][number]["effort"]) {
  if (effort === "alto") return "Alto";
  if (effort === "medio") return "Médio";
  return "Baixo";
}
